### ISSUE TITLE
Avoid reading from the HDF5 file.

### ISSUE THREAD

**Issue by emileten** [stactools-packages/nisar-sim#3]
**Is your feature request related to a problem? Please describe.**

Currently, a subset of the metadata is obtained directly from the HDF5 metadata. Absent other solutions, this requires reading the HDF5 file and therefore downloading it locally (a single file is usually over a couple GiBs), although we don't actually use its data. The cost is significant if we want to create STAC records for all the simulated data.

**Describe the solution you'd like**

We should request from the NISAR team that they add necessary metadata to the other files in the next versions of this data. 

**Describe alternatives you've considered**

For now we suggest that we :

- Drop the SAT extension, which requires information present only in the HDF5 metadata.
- Obtain the spatial and temporal extent information from the annotated files rather than the HDF5 file. 
 
**Additional context**

None.

cc @jjfrench @wildintellect

**Comment by sharkinsspatial** [comment]
@emileten As outlined in https://github.com/stactools-packages/nisar-sim/issues/5.  This package should be using fsspec for io.  Under no circumstances should ever need to locally download a file, this is the reason all stactools packages are built with the `use_fsspec` option auto-enabled for their cli mode.  

Rather than make upstream alterations to the data I'd suggest updating the package to use fsspec which will remotely read only the necessary byte ranges.

**Comment by emileten** [comment]
@sharkinsspatial i think you know that already but the only thing we have access to for now are download URLs starting with
 
https://downloaduav.jpl.nasa.gov/

Are you suggesting that we use fsspec with this to read part of, say, the hdf5 file only ?

**Comment by emileten** [comment]
For the record, Sean provided us with a solution to read only the metadata of the hdf5 through the above URL.
